version: '3.7'

services:
  session_db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sessiondb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - "./db/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db/data.sql:/docker-entrypoint-initdb.d/2.sql"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55


  session_service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      session_db:
        condition: service_healthy
    image: session-service:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      JDBC_DATABASE_URL: jdbc:mysql://session_db:3306/sessiondb?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      JDBC_DATABASE_PASSWORD: admin
      JDBC_DATABASE_USERNAME: admin