version: '3.7'

services:
  session_service:
    build:
      context: .
      dockerfile: Dockerfile
    # depends_on: # TODO: this will not be managed by docker-compose if db and service are in different stacks
    #   session_db:
    #     condition: service_healthy
    image: session-service:latest
    restart: always
    ports:
      - 8084:8084
    environment:
      JDBC_DATABASE_URL: jdbc:mysql://session_db:3306/sessiondb?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      JDBC_DATABASE_PASSWORD: admin
      JDBC_DATABASE_USERNAME: admin
    networks:
      - session-network
      - session-db-network
networks: 
  session-network:
    name: session-network
  session-db-network:
    name: session-db-network