name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # add here to test with different os
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package -Dmaven.test.skip=true --file pom.xml

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Service image
      run: docker build --tag khalld/session-service:latest .

    - name: Push Service on docker Hub
      run: docker push khalld/session-service:latest
    
    - name: Build Docker Redis image
      run: docker build --tag khalld/session-redis-store:latest ./redis

    - name: Push Redis on docker Hub
      run: docker push khalld/session-redis-store:latest
